config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
    post 'sign_up', to: 'devise/registrations#create'
    get 'sign_in', to: 'devise/sessions#new'
    post 'sign_in', to: 'devise/sessions#create'
    get 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    delete 'sign_out', to: 'devise/sessions#destroy'
    get 'profile/edit', to: 'devise/registrations#edit'

  end
  resources :users, only: [:show], constraints: { user_url: /\d.+/ } #:constraints => { :id => /[0-9|]+/ }
  resources :friendships, only: [:create, :destroy]
  resources :user_stocks, only: [:create, :destroy]
  get 'search', to: 'stock#search'
  get 'search_friend', to: 'users#search'
  get 'portfolio', to: 'users#portfolio'
  root 'home#index'
  get 'home/index'
  get 'pricing', to: 'home#pricing'
  get 'friends', to: 'users#friends'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable, :lockable, :timeoutable, :trackable, 
         :omniauthable

  has_many :user_stocks, dependent: :destroy
  has_many :stocks, through: :user_stocks
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  before_save { self.name.downcase!}
  before_save { self.email.downcase!}



  extend FriendlyId
  friendly_id :name, use: :slugged
  
  has_one_attached :avatar
  after_commit :add_default_avatar, on: %i[ update ]
  


  def self.search(param)
    param.strip!
    result = (name_matches(param) + email_matches(param)).uniq
    return nil unless result
    result
  end

  def self.name_matches(param)
    matches('name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param.downcase}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friend_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end


  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name 
  "Anonymous"
  end


  def stock_already_tracked?(stock_symbol)
    stock = Stock.check_db(stock_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def stock_limit?
    stocks.count < 12
  end

  def track_stock?(stock_symbol)
    stock_limit? && !stock_already_tracked?(stock_symbol)
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      user.gender = auth.info.gender   # assuming the user model has a name
      user.birthday = auth.info.birthday   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!
    end
  end

  def avatar_thumbnail
    # if avatar.attached?
    # avatar.variant(resize: "150x150!").processed
    # else
      "/default_avatar.jpg"
    # end
  end

  private
  def add_default_avatar
    unless avatar.attached?
      avatar.attach(
        io: File.open(
          Rails.root.join( 'app', 'assets', 'images', 'default_avatar.jpg')
        ), filename: 'default_avatar.jpg', content_type: 'image/jpg'
      )
    end
  end
        
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
    def google
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])
    
        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
          flash[:notice] = "Signed in successfully. " if is_navigational_format?
        else
          session["devise.google_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
          redirect_to new_user_registration_url
        end
      end
    
      def failure
        flash[:alert] = 'There was a problem signing you in. Please register or try signing in later.'
        redirect_to root_path
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! 
  def portfolio
    @tracked = current_user.stocks
    @user = current_user
  end

  def show
    @user = User.friendly.find(params[:id])
    @tracked = @user.stocks
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: 'users/friend_result' }
        end
      end    
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end

  def friends
    @friends = current_user.friends
  end

  def destroy 
    @user = User.find_by(id: params[:id])
    delete_user_data
    @user.destroy 

    # probably a redirect would happen down here  
  end 
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def delete_user_data
    @user.user_stocks.destroy_all
    @user.friendships.destroy_all 
  end 
end

app/views/users/_friend_result.html.erb
 
 
<%= render "shared/info" %>

<% if @friends %>
  <div class="card mt-5">
    <div class="card-body">
      <table class="col-sm-12">
        <% @friends.each do |friend| %>
          <tbody>
            <tr>
              <td><strong class='me-3'>Name:</strong><%= friend.name %></td>
              <td><strong class='me-3 ms-4'>Email Address:</strong><%= friend.email %></td>
              <td><strong class=' ms-4'>Profile:</strong><%= link_to "View Profile", user_path(friend), class: 'badge bg-secondary lk ms-3'%>
              <% if current_user.not_friend_with?(friend.id) %>
              <%= link_to "Follow Friend", friendships_path(friend: friend), class: 'btn btn-success btn-sm ms-3', method: :post %>
              <% else %>
                <span class="badge bg-dark">You are friends</span>
              <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>' 

app/views/users/friends.html.erb
<header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-5 border-bottom">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal">My Friends</h1>
      <p class="fs-5 text-muted">Quickly build an effective pricing table for your potential customers.</p>
    </div>
</header>
<div class="row">
  <div class="col-sm-6 mx-auto mb-0">
    <h3 class="mb-0">
    Search friends 
    </h3> 
  </div>
</div>

<form action="<%= search_friend_path %>" data-remote="true" method="get">
  <div class="row mt-4">
    <div class="col-sm-6 mx-auto d-flex">
      <input class="form-control form-control-lg" name="friend" id="friend" type="search" placeholder="Search friends" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </div>

    <div class="row mt-3">
      <div class="col-sm-10 mx-auto d-flex">
        <div id="friend-results">
        </div>
      </div>
    </div>

    <div class="col-sm-10 mx-auto d-flex mt-3">
    <% if !@friends.empty?%>
      <%= render "shared/list" %>
      <% end %>
    </div>
  </div>
</form>

app/views/users/portfolio.html.erb
<header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-5 border-bottom">
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal">My Portfolio</h1>
      <p class="fs-5 text-muted">Quickly build an effective pricing table for your potential customers.</p>
    </div>
</header>


<form action="<%= search_path %>" data-remote="true" method="get">
 <div class="row">

  <div class="col-sm-8 mx-auto d-flex">
    <input class="form-control form-control-lg" name="stock" id="stock" type="search" placeholder="Search Stocks by Symbol" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Search  </button>
  </div>
  
  <div class="row mt-4">
    <div class="col-sm-10 mx-auto d-flex">
      <div id="result">
      </div>
    </div>
  </div>

   <div class="row mt-4">
    <div class="col-sm-10 mx-auto d-flex">
      <% if !@tracked.empty?%>
        <%= render "stock/list" %>
      <% end %>
    </div>
  </div>
  </div>
 </div>
</form> 

app/views/users/show.html.erb
<div class="container rounded bg-white mt-5 mb-5">
  <div class="row">
    <div class="col-md-4 border-right bg-light">
      <div class="d-flex flex-column align-items-center text-center p-3 py-5">
      <%= image_tag(@user.avatar, class: "rounded-circle mt-5 mb-2", width: "150", height: "150") %>
        <span class="font-weight-bold text-capitalize"><%= @user.name%></span>
        <span class=" badge bg-secondary text-white ps-3 pe-3 mb-3"><%= @user.email%></span>
        
        <% if current_user.not_friend_with?(@user) %>
            <%= link_to "Add Friend", friendships_path(friend: @user), class: 'btn btn-success btn-sm ', method: :post %>
          <% else %>
            <span class="badge bg-dark">You are friends</span>
        <% end %> 

      </div>
    </div>

    <div class="col-md-8 border-right">
      <div class="p-3 py-5">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h4 class="text-right text-capitalize"><%= @user.name%> stocks</h4>
        </div>

          <% if !@tracked.empty?%>
              <%= render "stock/list" %>
            <% else%>
              <p class="badge bg-dark text-capitalize fs-5"><%= @user.name%> is not tracking any stock</p>
          <% end %>
      </div>
    </div>

</div>