config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
    post 'sign_up', to: 'devise/registrations#create'
    get 'sign_in', to: 'devise/sessions#new'
    post 'sign_in', to: 'devise/sessions#create'
    get 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    delete 'sign_out', to: 'devise/sessions#destroy'
    get 'profile/edit', to: 'devise/registrations#edit'

  end
  resources :users, only: [:show], constraints: { user_url: /\d.+/ } #:constraints => { :id => /[0-9|]+/ }
  resources :friendships, only: [:create, :destroy]
  resources :user_stocks, only: [:create, :destroy]
  get 'search', to: 'stock#search'
  get 'search_friend', to: 'users#search'
  get 'portfolio', to: 'users#portfolio'
  root 'home#index'
  get 'home/index'
  get 'pricing', to: 'home#pricing'
  get 'friends', to: 'users#friends'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="row row-cols-5 py-5 my-5 border-top">
    <div class="col">
      <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <p class="text-muted">© 2021</p>
    </div>

    <div class="col">

    </div>

    <div class="col">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>

    <div class="col">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>

    <div class="col">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>
  </footer>
</div>

app/views/shared/_info.html.erb
<% if notice.present? %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <div class="notice"><%= notice %></div>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

<% if alert.present? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <div class="alert"><%= alert %></div>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/shared/_list.html.erb
<table class="table table-bordered table-hover table-sm">
  <thead>
    <tr>
    <th scope="col">Email Address</th>
    <th scope="col">Full Name</th>
    <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @friends.each do | friend | %>
    <tr>
    <td class=""><%= friend.email %></td>
    <td><%= friend.name %></td>
    <td><%= link_to "unfollow", friendship_path(friend), class: 'badge bg-danger lk badge-sm', method: :delete, data: {confirm: 'Do you want to stop following this friend?'} %>
        <%= link_to "View Profile", user_path(friend), class: 'badge bg-secondary lk ms-3'%></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/shared/_nav.html.erb
<header class="hgt">
  <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
    <div class="container">
      <a class="navbar-brand" href="/"> <i class="bi bi-stack text-success"></i> StockApp</a>
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbarCollapse" style="">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link <%= 'active' if request.path == portfolio_path%>" aria-current="page" href="/portfolio">Portfolio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link <%= 'active' if request.path == friends_path%>" href="/friends">Friends</a>
          </li>
          <li class="nav-item">
            <a href='/pricing' class="nav-link <%= 'active' if request.path == pricing_path%>">Pricing</a>
          </li>
        </ul>
        <% if user_signed_in?%>
        <ul class="navbar-nav">
           <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-capitalize lk" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <%= image_tag(current_user.avatar, width: "30", height: "30", style: "border-radius: 50%") if current_user.avatar.attached? %>
                <%= current_user.name %>
              </a>
              <div class="dropdown-menu dropdown-menu-end">
                <a class="dropdown-item text-capitalize" href="#"><%= current_user.name %> <br> <span class="text-lowercase"><%= current_user.email %></span></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#"><i class="bi bi-bell"></i> Notifications <span class="badge bg-secondary">4</span></a>
                <a class="dropdown-item text-success" href="/pricing"><i class="bi bi-person-check"></i> Become a pro Member</a>
                <a class="dropdown-item" href="/" target="_blank"><i class="bi bi-life-preserver"></i> Help /Support</a>
                <a class="dropdown-item" href="/profile/edit"><i class="bi bi-gear-wide-connected"></i> User Settings</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item text-danger" href="/sign_out"><i class="bi bi-box-arrow-right"></i> Sign Out</a>
              </div>
            </li>
        </ul>
        <% else %>
          <a class='btn btn-outline-success me-2' href="/sign_in">sign in</a>
          <a class='btn btn-success' href="/sign_up">sign up</a>
        <% end %>
        <%
=begin%>
 <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> 
<%
=end%>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_result.html.erb
 
 
<%= render "shared/info" %>

<% if @stock %>
    <div class="card mt-5">
      <div class="card-body">
      <strong class='me-3 ms-4'>Stock Symbol:</strong><span class="text-uppercase"><%= @stock.symbol %></span>
      <strong class='me-3 ms-4'>Company:</strong><%= @stock.company %>
      <strong class='me-3 ms-4'>Stock Price:</strong><%= @stock.last_price %>
      <% if current_user.track_stock?(@stock.symbol)%>
          <%= link_to "Add to portfolio", user_stocks_path(user: current_user, symbol: @stock.symbol), class: 'btn btn-success btn-sm ms-3', method: :post %>
      <% else %>
        <span class="badge bg-secondary">You are already tracking 
          <% if !current_user.stock_limit?%>
            12 stocks
          <% end %>
           <% if current_user.stock_already_tracked?(@stock.symbol)%>
            this stock
          <% end %>
        </span>

          <% if !current_user.stock_limit? %>
           <%= link_to "upgrade plan", pricing_path %> 
          <% end %>
         
      <% end %>
      </div>
      
    </div>
<% end %>

app/views/shared/_result.js.erb
document.querySelector('#result').innerHTML = '<%= j render 'shared/result.html' %>'