config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
    post 'sign_up', to: 'devise/registrations#create'
    get 'sign_in', to: 'devise/sessions#new'
    post 'sign_in', to: 'devise/sessions#create'
    get 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    delete 'sign_out', to: 'devise/sessions#destroy'
    get 'profile/edit', to: 'devise/registrations#edit'

  end
  resources :users, only: [:show], constraints: { user_url: /\d.+/ } #:constraints => { :id => /[0-9|]+/ }
  resources :friendships, only: [:create, :destroy]
  resources :user_stocks, only: [:create, :destroy]
  get 'search', to: 'stock#search'
  get 'search_friend', to: 'users#search'
  get 'portfolio', to: 'users#portfolio'
  root 'home#index'
  get 'home/index'
  get 'pricing', to: 'home#pricing'
  get 'friends', to: 'users#friends'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks, dependent: :delete_all
  has_many :users, through: :user_stocks
  validates :symbol, :company, presence: true
  before_save { self.symbol.downcase!}

  extend FriendlyId
  friendly_id :company, use: :slugged

  def self.new_lookup(stock_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_key[:iex_id],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )    
    
    begin
      new(symbol: stock_symbol, last_price: client.price(stock_symbol), company: client.company(stock_symbol).company_name )
    rescue => exception
      return nil
    end
  end

  def self.check_db(stock_symbol)
    where(symbol: stock_symbol).first
  end
end

app/controllers/stock_controller.rb
class StockController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do | format |
          format.js { render partial: 'shared/result'}
        end
      else
        respond_to do | format |
          flash.now[:alert] = 'Please enter a valid stock symbol to lookup!'
          format.js { render partial: 'shared/result'}
        end
      end
    else
      respond_to do | format |
        flash.now[:alert] = 'Please enter a stock symbol to lookup!'
        format.js { render partial: 'shared/result'}
      end
    end
  end
end
  

app/helpers/stock_helper.rb
module StockHelper
end

app/views/stock/_list.html.erb
      
      
<table class="table table-bordered table-hover table-sm">
  <thead>
    <tr>
    <th scope="col">Stock Symbol</th>
    <th scope="col">Company</th>
    <th scope="col">Stock Price</th>
    <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @tracked.each do | stock | %>
    <tr>
    <td class="text-uppercase"><%= stock.symbol %></td>
    <td><%= stock.company %></td>
    <td><%= stock.last_price %></td>
    <td>
    <% if @user == current_user%>
      <%= link_to "Remove", user_stock_path(stock), class: 'badge bg-danger lk badge-sm', method: :delete, data: {confirm: 'Are you sure?'} %>
      <% else %>
      <% if current_user.track_stock?(stock.symbol)%>
          <%= link_to "Add to portfolio", user_stocks_path(user: current_user, symbol: stock.symbol), class: 'btn btn-success btn-sm ms-3', method: :post %>
      <% else %>
        <span class="badge bg-secondary">You are already tracking 
          <% if !current_user.stock_limit?%>
            10 stocks
          <% end %>
           <% if current_user.stock_already_tracked?(stock.symbol)%>
            this stock
          <% end %>
        </span>

          <% if !current_user.stock_limit?%>
           <%= link_to "upgrade plan", pricing_path %>
          <% end %>
         
      <% end %>
    <% end %>
    </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/stock/search.html.erb
<h1>Stock#search</h1>
<p>Find me in app/views/stock/search.html.erb</p>